<?php use \Phalcon\Tag as Tag; ?>
<?php $dlIcon = Tag::image('img/download30x30.png'); ?>
<?php $githubIcon = Tag::image('img/github30x30.png'); ?>
<?php $pearIcon = Tag::image('img/pear32x32.gif'); ?>
<?php echo Tag::stylesheetLink("css/colors/zenburn.css"); ?>

<div class="doc-box">
	<table width="60%" align="center">
		<tr>
			<td><?php echo Tag::image('img/download.png') ?></td>
			<td>
				<h2>Downloads</h2>
				Phalcon is a C extension so you need to download a binary for your platform or compile
				it from source code.
			</td>
		</tr>
	</table>
</div>

<table align="center" class="tableFormat2" width="80%" cellspacing="15">
	<tr>
		<td valign="top">
			<table align="center" class="tableFormat1" valign="top" cellpadding="5" cellspacing="0">

				<tr>
					<th colspan="3" class="titleContent">Phalcon PHP</th>
				</tr>
                <?php foreach ($current as $version_key => $version) { ?>
				<tr class="cellDown">
					<td align="left" colspan="2">
                        <strong><?php echo $version_key; ?></strong>
                    </td>
				</tr>
                <?php foreach ($version as $file) { ?>
				<tr class="cellDown">
					<td align="left">
                        <?php echo Tag::linkTo(array($file['file'], $dlIcon, 'target' => '_download')); ?>
                    </td>
                    <td align="left">
                        <?php echo $file['name']; ?>
                        <br />
                        <span>Updated: <?php echo $file['date']; ?></span>
                    </td>
				</tr>
                <?php } ?>
                <?php } ?>
				<tr class="cellDown">
                    <td align="left">
                        <a target="_download" href="https://github.com/phalcon/cphalcon/"><?php echo $githubIcon; ?></a>
                    </td>
                    <td align="left">
					    Phalcon 0.5.0 - Source-Code
                    </td>
				</tr>

                <tr><td><br /></td></tr>

                <tr>
                    <th colspan="3" class="titleContent">Developer Tools</th>
                </tr>
                <tr class="cellDown">
                    <td align="left">
                        <a target="_download" href="https://github.com/phalcon/phalcon-devtools/zipball/master"><?php echo $githubIcon; ?></a>
                        <a href="http://pear.phalconphp.com/"><?php echo $pearIcon; ?></a>
                    </td>
                    <td align="left">
                        Phalcon Developer Tools
                    </td>
                </tr>

                <tr><td><br /><br /></td></tr>

                <tr>
                    <th colspan="3" class="titleContent">Older versions</th>
                </tr>
                <?php foreach ($old as $version_key => $version) { ?>
				<tr class="cellDown">
					<td align="left" colspan="2">
                        <strong><?php echo $version_key; ?></strong>
                    </td>
				</tr>
                <?php foreach ($version as $file) { ?>
				<tr class="cellDown">
					<td align="left">
                        <?php echo Tag::linkTo(array($file['file'], $dlIcon, 'target' => '_download')); ?>
                    </td>
                    <td align="left">
                        <?php echo $file['name']; ?>
                        <br />
                        Updated: <?php echo $file['date']; ?>
                    </td>
				</tr>
                <?php } ?>
                <?php } ?>
				<tr class="cellDown">
                    <td align="left">
                        <a target="_download" href="https://github.com/phalcon/cphalcon/"><?php echo $githubIcon; ?></a>
                    </td>
                    <td align="left">
					    Phalcon 0.4.5 - Source-Code
                    </td>
				</tr>
                <tr>
                    <td colspan="2">
                        <div class="highlightb">
                            We highly recommend you to use the latest version of PHP 5.3 to achieve
                            maximum stability with Phalcon.
                        </div>
                    </td>
                </tr>
			</table>
		</td>
		<td width="50%" valign="top" style="padding-left:15px">
			<div valign="top" align="left">

				<div class="titleContent">Get Started</div>
				<br/>
				Phalcon PHP is written in C with platform independence in mind.
    			As a result, Phalcon PHP is available on
			    <a href="http://www.microsoft.com/windows">Microsoft Windows</a>,
			    <a href="http://kernel.org">GNU/Linux</a>,
			    <a href="http://www.freebsd.org/">FreeBSD</a>
			    <a href="http://www.apple.com">Mac OS X</a>,
			    You can either download a binary package for the system of your choice or
			    build it from sources.</p>

			    <h3>Windows</h3>
			    To use phalcon on Windows you can download a DLL library.
			    Edit your php.ini and append at the end:

			    <pre class="source-code php">extension=php_phalcon.dll</pre>

				Restart your webserver to load the extension.

			    <h3>Linux</h3>
				On platform Linux you can easily compile and install the extension from source code.

			    <h4>Requirements</h4>
			    We need some packages previously installed

			    <ul>
			    	<li>PHP 5.x development resources</li>
			    	<li>GCC compiler</li>
			    </ul>

			    <pre class="source-code php">
#Ubuntu
sudo apt-get install php5-dev php5-mysql gcc

#Suse
yast2 -i php5-pear php5-dev php5-mysql gcc</pre>

			    <h4>Compilation</h4>
			    To create the extension from C source follow the next steps:
			    <pre class="source-code php">
git clone git://github.com/phalcon/cphalcon.git
cd cphalcon/build
export CC="gcc"
export CFLAGS="-O2 -fno-delete-null-pointer-checks"
phpize
./configure --enable-phalcon
make && sudo make install
</pre>

Add the extension to your php.ini:
<pre class="source-code php">extension=phalcon.so</pre>

			    Finally restart the webserver

			    <h3>Arch Linux</h3>
			    There is a PKGBUILD for ArchLinux, available <a href="http://aur.archlinux.org/packages.php?ID=61950">here</a>

			    <h3>FreeBSD</h3>
				A port is available for FreeBSD. Just only need these simple line commands to install it:
				<pre class="source-code php">
# pkg_add -r phalcon
</pre>
or
<pre class="source-code php">
# cd /usr/ports/www/phalcon && make install clean
				</pre>

			    <h4>Need help?</h4>
			    Please send us a ticket at <a href="https://github.com/phalcon/cphalcon/issues">Github</a>
			    or contact us at our <a href="http://phalcon.uservoice.com/">Help Desk</a> and let us to help you.

			</div>
		</td>
	</tr>
</table>
