
<?php echo Phalcon\Tag::stylesheetLink("css/colors/zenburn.css") ?>

<div class="doc-box">
	<table width="60%" align="center">
		<tr>
			<td><?php echo Phalcon\Tag::image('img/download.png') ?></td>
			<td>
				<h2>Downloads</h2>
				Phalcon is a C extension so you need to download a binary for your platform or compile
				it from source code.
			</td>
		</tr>
	</table>
</div>

<table align="center" class="tableFormat2" width="80%" cellspacing="15">
	<tr>
		<td valign="top">
			<table align="center" class="tableFormat1" valign="top" cellpadding="5" cellspacing="0">
				<tr>
					<th colspan="3"><div class="titleContent">Phalcon PHP</div></th>
				</tr>
				<tr class="cellDown">
					<td align="left">Phalcon 0.4.5 - Windows x86 for PHP 5.3 (VC9)</td>
					<td align="center"><?php echo Phalcon\Tag::linkTo(array('files/phalcon-win-x86-php5.3-0.4-VC9.zip','download','target'=>'_download')); ?></td>
				</tr>
				<tr class="cellDown">
					<td align="left">Phalcon 0.4.5 - Windows x86 for PHP 5.5 (VC9)</td>
					<td align="center"><?php echo Phalcon\Tag::linkTo(array('files/phalcon-win-x86-php5.4-0.4-VC9.zip','download','target'=>'_download')); ?></td>
				</tr>
				<tr class="cellDown">
					<td align="left">Phalcon 0.4.4 - Windows x64 for PHP 5.3 (VC9)</td>
					<td align="center"><?php echo Phalcon\Tag::linkTo(array('files/phalcon-win-x64-php5.3-0.4-VC9.zip','download','target'=>'_download')); ?></td>
				</tr>
				<tr class="cellDown">
					<td align="left">Phalcon 0.4.4 - Source-Code</td>
					<td align="center"><a target="_download" href="https://github.com/phalcon/cphalcon/">clone</a></td>
				</tr>
				<tr><td><br><br></td></tr>
				<tr>
					<th colspan="3"><b>Phalcon PHP (alpha)</b></th>
				</tr>
				<tr class="cellDown">
					<td align="left">Phalcon 0.5.0b1 - Windows x86 for PHP &lt;= 5.3.8 (VC9)</td>
					<td align="center"><?php echo Phalcon\Tag::linkTo(array('files/phalcon-win-x86-php5.3-0.5-VC9.zip','download','target'=>'_download')); ?></td>
				</tr>
				<tr class="cellDown">
					<td align="left">Phalcon 0.5.0b1 - Windows x86 for PHP &gt; 5.3.8 (VC9)</td>
					<td align="center"><?php echo Phalcon\Tag::linkTo(array('files/phalcon-win-x86-php5.3.8-0.5-VC9.zip','download','target'=>'_download')); ?></td>
				</tr>
				<tr class="cellDown">
					<td align="left">Phalcon 0.5.0b1 - Windows x86 for PHP 5.4 (VC9)</td>
					<td align="center"><?php echo Phalcon\Tag::linkTo(array('files/phalcon-win-x86-php5.4-0.5-VC9.zip','download','target'=>'_download')); ?></td>
				</tr>
				<tr class="cellDown">
					<td align="left">Phalcon 0.5.0b1 - Source-Code</td>
					<td align="center"><a target="_download" href="https://github.com/phalcon/cphalcon/">clone</a></td>
				</tr>
				<tr>
					<td colspan="2">
						<div class="highlightb">
							We highly recommend you to use the lastest version of PHP 5.3 to achieve maximum stability with Phalcon.
						</div>
					</td>
				</tr>
				<tr><td><br></td></tr>
				<tr>
					<th colspan="3"><b>Developer Tools</b></th>
				</tr>
				<tr class="cellDown">
					<td align="left">Phalcon Developer Tools</td>
					<td align="center"><a href="https://github.com/phalcon/phalcon-devtools/zipball/master">download</a></td>
				</tr>
			</table>
		</td>
		<td width="50%" valign="top" style="padding-left:15px">
			<div valign="top" align="left">

				<div class="titleContent">Get Started</div>
				<br/>
				Phalcon PHP is written in C with platform independence in mind.
    			As a result, Phalcon PHP is available on
			    <a href="http://www.microsoft.com/windows">Microsoft Windows</a>,
			    <a href="http://kernel.org">GNU/Linux</a>,
			    <a href="http://www.freebsd.org/">FreeBSD</a>
			    <a href="http://www.apple.com">Mac OS X</a>,
			    You can either download a binary package for the system of your choice or
			    build it from sources.</p>

			    <h3>Windows</h3>
			    To use phalcon on Windows you can download a DLL library.
			    Edit your php.ini and append at the end:

			    <pre class="source-code php">extension=php_phalcon.dll</pre>

				Restart your webserver to load the extension.

			    <h3>Linux</h3>
				On platform Linux you can easily compile and install the extension from source code.

			    <h4>Requirements</h4>
			    We need some packages previously installed

			    <ul>
			    	<li>PHP 5.x development resources</li>
			    	<li>GCC compiler</li>
			    </ul>

			    <pre class="source-code php">
#Ubuntu
sudo apt-get install php5-dev php5-mysql gcc

#Suse
yast2 -i php5-pear php5-dev php5-mysql gcc</pre>

			    <h4>Compilation</h4>
			    To create the extension from C source follow the next steps:
			    <pre class="source-code php">
# git clone git://github.com/phalcon/cphalcon.git
# cd cphalcon/release
# export CFLAGS="-O2 -fno-delete-null-pointer-checks"
# phpize
# ./configure --enable-phalcon
# make && sudo make install
</pre>

Add the extension to your php.ini:
<pre class="source-code php">extension=phalcon.so</pre>

			    Finally restart the webserver

			    <h3>Arch Linux</h3>
			    There is a PKGBUILD for ArchLinux, available <a href="http://aur.archlinux.org/packages.php?ID=61950">here</a>

			    <h3>FreeBSD</h3>
				A port is available for FreeBSD. Just only need these simple line commands to install it:
				<pre class="source-code php">
# pkg_add -r phalcon
</pre>
or
<pre class="source-code php">
# cd /usr/ports/www/phalcon && make install clean
				</pre>

			    <h4>Need help?</h4>
			    Please send us a ticket at <a href="https://github.com/phalcon/cphalcon/issues">Github</a>
			    or contact us at our <a href="http://phalcon.uservoice.com/">Help Desk</a> and let us to help you.

			</div>
		</td>
	</tr>
</table>
