<?php use Phalcon\Tag as Tag; ?>
<?php echo $this->getContent() ?>

<div align="left">
    <div id="main-content">
        <table align="center" class="main-table">
            <tr>
                <td valign="top">
                    <div class="name">
                        Welcome<br/>
                        <div class="subname">TO THE FASTEST<br/>PHP FRAMEWORK</div>
                        <p>PhalconPHP is a web framework delivered as a C extension
                            providing
                            <a href="http://docs.phalconphp.com/en/latest/reference/benchmark.html">high performance</a>
                            and lower resource consumption
                        </p>
                        <table align="center">
                            <tr>
                                <td align="center">
                                    <?php echo Tag::linkTo(array('documentation', '<div class="documentation">See documentation</div>', 'class' => 'no-decoration')) ?>
                                </td>
                                <td align="center">
                                    <?php echo Tag::linkTo(array('download', '<div class="download">Download</div>', 'class' => 'no-decoration')) ?>
                                </td>
                            </tr>
                        </table>
                    </div>
                </td>
                <td width="45%" id="speakerdeck">
                    <div id="speakerdeck_presentation_wrapper_4edf11f72a2b980050009919">
                        <iframe class="present_iframe" frameBorder="0" allowTransparency="true" mozallowfullscreen="true" webkitallowfullscreen="true" id="presentation_frame_4edf11f72a2b980050009919" src="//speakerdeck.com/embed/4edf11f72a2b980050009919?size=preview&slide=1" width="400" height="364"></iframe>
                    </div>
                </td>
            </tr>
        </table>
    </div>
</div>

<div align="center">
    <div class="sub-content">
        <div class="sub">
            <?php echo Tag::linkTo('download', Tag::image(array('img/download.png', 'border' => '0')).
            '<br/>Download and Try<br/><span>C extensions are available for many platforms</span>') ?><br/>
        </div>
        <div class="sub">
            <?php echo Tag::linkTo('documentation', Tag::image(array('img/book.png', 'border' => '0')).
            '<br/>Learn and Enjoy<br/><span>Read updated documentation and guides</span>') ?>
        </div>
        <div class="sub">
            <a href="https://twitter.com/phalconphp"><?php echo Tag::image(array('img/chat.png', 'border' => '0')).
            '<br/>Share and Socialize<br/><span>Tell your friends about the Phalcon framework in social networks</span>' ?></a>
        </div>
    </div>
</div>

<div id="github-con">
    <div id="github" style="display:none">
        <a href="https://github.com/phalcon/cphalcon">Watch me on Github</a>
    </div>
</div>
