
<div class="nav-bar">
	<?php echo Phalcon\Tag::linkTo('index', 'Home') ?> » Documentation
</div>

<div class="doc-paragraph">
	<h2>Screencasts</h2>
	Check out the latest screencasts we published in our <a href="https://vimeo.com/user10964377/videos">Vimeo Channel</a>:
</div>

<div class="doc-paragraph">
	<h3>Phalcon integration with PhpStorm IDE</h3>
	This screencast shows how you can integrate Phalcon Framework/Developer Tools with PhpStorm IDE.
</div>

<div class="doc-center">
	<iframe src="http://player.vimeo.com/video/43455647?color=72b395" width="600" height="338" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
</div>

<p></p>

<div class="doc-paragraph">
	<h3>Phalcon Developer Tools: Web Interface</h3>
	WebTools, same Phalcon Developer tools but now with a beautiful web interface, allowing you to be more productive without extra complications.
</div>

<div class="doc-center">
	<iframe src="http://player.vimeo.com/video/42367665?color=72b395" width="600" height="338" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
</div>

<p></p>

<div class="doc-paragraph">
	<h3>Phalcon Developer Tools - Database Migrations</h3>
	Migrations are a convenient way for you to alter your database in a structured and organized manner. This screencast shows how to generate and run database migrations using Developer Tools.
</div>

<div class="doc-center">
	<iframe src="http://player.vimeo.com/video/41381817?color=72b395" width="600" height="338" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
</div>

<p></p>

<div class="doc-paragraph">
	<h3>Phalcon Developer Tools - Creating Models</h3>
	This screencast shows how to generate models using Developer Tools. Our approach of model generation, focuses on maintain specific changes after add or remove fields. By this way, the developer does not have to be worried about losing his work after re-generate the model.
</div>

<div class="doc-center">
	<iframe src="http://player.vimeo.com/video/39213020?color=72b395" width="600" height="338" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
</div>

<p></p>

<div class="doc-paragraph">
	<h3>Phalcon Developers Tools</h3>
	Screencast explaining the basic usage of Phalcon Developer Tools.
</div>

<div class="doc-center">
	<iframe src="http://player.vimeo.com/video/39035250?color=72b395" width="600" height="337" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
</div>

<div class="nav-bar">
	<table width="90%" align="center">
		<tr>
			<td align="left">
				<?php echo Phalcon\Tag::linkTo('documentation/api', '← Framework API') ?>
			</td>
			<td align="right">
				<?php echo Phalcon\Tag::linkTo('documentation/license', 'License →') ?>
			</td>
		</tr>
	</table>
</div>
