
<div class="nav-bar">
	<?php echo Phalcon_Tag::linkTo('index', 'Home') ?> » Documentation
</div>

<div class="doc-paragraph">
	<h2>Improving Performance with Cache</h2>
	Phalcon provides the <?php echo Tag::classLink('Phalcon_Cache') ?>, it help us to cache output fragments
	avoiding the continuous reprocessing of code that every time returns the same output.
</div>

<div class="doc-paragraph">
	Phalcon_Cache is very similar to the Zend Framework counterpart but is written in C to reach high performance.
	This component uses an internal structure of frontends and backends. Frontends acts as input sources and
	backends provides storage features.
</div>

<div class="doc-paragraph">
	<h3><a name="when">When to implement cache?</a></h3>
	Although this component is very fast, implementing it in unnecessary cases could lead to loss of
	performance rather than get it. We recommend you check this cases before use cache:
	<ul>
		<li>You are making complex calculations that everytime returns the same result (changing infrequently)</li>
		<li>You are using a lot of helpers and the output generated is almost always the same</li>
		<li>You are accessing database data constantly and these data rarely change</li>
	</ul>
</div>

<div class="doc-paragraph">
	<h3><a name="output">Caching Output Fragments</a></h3>
	The following example shows how to implement a cache using this component. It takes the output generated
	by PHP and stores it into a file. The content of the file is refreshed each 172800 seconds (2 days).
	The implementation of the cache avoids the continuous execution of the helper Phalcon_Tag::linkTo.
</div>

<div class="doc-center">
<?php echo hyperlight('<?php

//Cache the files for 2 days
$frontendOptions = array(
  "lifetime" => 172800
);

//Set the cache file directory
$backendOptions = array(
  "cacheDir" => "../app/cache/"
);

//Create a cache that caches from the "Output" to a "File" backend
$cache = Phalcon_Cache::factory("Output", "File",
   $frontendOptions, $backendOptions);

//Get/Set the cache file to ../app/cache/my-cache.html
$content = $cache->start("my-cache.html");

//If $content is null then the content will be created or will refreshed
if ($content === null) {

  //Print date and time
  echo date("r");

  //Generate a link to the sign-up action
  echo Phalcon_Tag::linkTo(array(
    "user/signup",
    "Sign Up",
    "class" => "signup-button"
  ));

  //Stores the output into cache file
  $cache->save();
} else {

  //Echo the cached output
  echo $content;
}
', 'php');

?>
</div>

<div class="doc-paragraph">
	<h3><a name="data">Caching Arbitrary Data</a></h3>
	Remember the situations mentioned above? Caching data is very useful to reduce access to
	database systems or avoid avoid heavy processing frequently.
</div>

<div class="doc-center">
<?php echo hyperlight('<?php

//Cache data for one hour
$frontendOptions = array(
  "lifetime" => 3600
);

//Memcached connection settings
$backendOptions = array(
  "host" => "localhost",
  "port" => "11211"
);

//Create a cache
$cache = Phalcon_Cache::factory("Data", "Memcached", $frontendOptions, $backendOptions);

//Try to get cached records
$robots = $cache->get("robots");
if($robots===null){

   //$robots are null due to cache expiration or data is nonexistent
   //Only here, the database system is accessed
   $robots = Robots::find(array("order" => "id"));

   $cache->save("robots", $robots);
}

//Use $robots normally
foreach($robots as $robot){
   echo $robot->name, "\n";
}

', 'php'); ?>
</div>

<div class="doc-paragraph">
	<h3><a name="querying">Querying the cache</a></h3>
	Insofar as we add items to the cache, they are uniquely identified with the keys used to store them.
	If the cached data has expired or the key is not existent in the cache the method get will return null.
</div>

<div class="doc-center">
<?php echo hyperlight('

//Retrieve products by key "myProducts"
$products = $cache->get("myProducts");

', 'iphp'); ?>
</div>

<div class="doc-paragraph">
	If you want to know which keys are stored in the cache you could call the queryKeys method:
</div>

<div class="doc-center">
<?php echo hyperlight('

//Query all keys used in the cache
$keys = $cache->queryKeys();
foreach($keys as $key){
	$data = $cache->get($key);
	echo "Key=", $key, " Data=", $data;
}

//Query keys in the cache that begins with "my-prefix"
$keys = $cache->queryKeys("my-prefix");

', 'iphp'); ?>
</div>

<div class="doc-paragraph">
	<h3><a name="deleting">Deleting from the Cache</a></h3>
	Additionally, sometimes may be necessary to remove items from the cache, this in order to force
	them to be refreshed from its origins. To delete an item you need to know the key with which it was created:
</div>

<div class="doc-center">
<?php echo hyperlight('

//Delete an item with a specific key
$cache->queryKeys("someKey");

//Delete all items from the cache
$keys = $cache->queryKeys();
foreach($keys as $key){
	$cache->delete($key);
}

', 'iphp'); ?>
</div>

<div class="doc-paragraph">
	<h3><a name="frontend">Frontend Adapters</a></h3>
	This component makes use of frontend adapters to encapsulate the different input sources to cache.
</div>

<div class="doc-paragraph">
	<table align="center" cellspacing="0">
		<tr>
			<th>Adapter</th>
			<th>Description</th>
		</tr>
		<tr>
			<td>Output</td>
			<td>Read input data from standard PHP output</td>
		</tr>
		<tr>
			<td>Data</td>
			<td>It's used to cache any kind of PHP data (big arrays, objects, text, etc).
				This adapter always serializes the data before store it into the backend.</td>
		</tr>
		<tr>
			<td>None</td>
			<td>It's used to cache any kind of PHP data without serializing them.</td>
		</tr>
	</table>
</div>

<div class="doc-paragraph">
	<h3><a name="backend">Backend Adapters</a></h3>
	Also, this component makes use of backend adapters to encapsulate storage details related to the cache.
</div>

<div class="doc-paragraph">
	<table align="center" cellspacing="0">
		<tr>
			<th>Adapter</th>
			<th>Description</th>
			<th>Info</th>
			<th>Required Extensions</th>
		</tr>
		<tr>
			<td>File</td>
			<td>Stores data to local plain files</td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td>Memcached</td>
			<td>Stores data to a memcached server</td>
			<td><a href="http://memcached.org/">Memcached</a></td>
			<td><a href="http://pecl.php.net/package/memcache">memcache</a></td>
		</tr>
		<tr>
			<td>APC</td>
			<td>Stores data to the Alternative PHP Cache (APC)</td>
			<td><a href="http://php.net/manual/en/book.apc.php">APC</a></td>
			<td><a href="http://pecl.php.net/package/APC">APC</a></td>
		</tr>
	</table>
</div>

<div class="doc-paragraph">
	<h4><a name="backend">File Backend</a></h4>
	This backend will store cached content into files in the local server. The available options for this
	backend are:
</div>

<div class="doc-paragraph">
	<table align="center" cellspacing="0">
		<tr>
			<th>Option</th>
			<th>Description</th>
		</tr>
		<tr>
			<td>cacheDir</td>
			<td>A writable directory on which cached files will be placed</td>
		</tr>
	</table>
</div>

<div class="doc-paragraph">
	<h4><a name="memcached">Memcached Backend</a></h4>
	This backend will store cached content on a memcached server. The available options for this
	backend are:
</div>

<div class="doc-paragraph">
	<table align="center" cellspacing="0">
		<tr>
			<th>Option</th>
			<th>Description</th>
		</tr>
		<tr>
			<td>host</td>
			<td>memcached host</td>
		</tr>
		<tr>
			<td>port</td>
			<td>memcached port</td>
		</tr>
		<tr>
			<td>persistent</td>
			<td>create a persitent connection to memcached?</td>
		</tr>
	</table>
</div>

<div class="doc-paragraph">
	<h4><a name="apc">APC Backend</a></h4>
	This backend will store cached content on Alternative PHP Cache (APC). This cache doesn't have any
	configuration.
</div>


<div class="nav-bar">
	<table width="90%" align="center">
		<tr>
			<td align="left">
				<?php echo Phalcon_Tag::linkTo('documentation/pagination', '← Data Pagination') ?>
			</td>
			<td align="right">
				<?php echo Phalcon_Tag::linkTo('documentation/acl', 'Access Control Lists (ACL) →') ?>
			</td>
		</tr>
	</table>
</div>
