
<div class="nav-bar">
	<?php echo Phalcon_Tag::linkTo('index', 'Home') ?> » Documentation
</div>

<div class="doc-box">
	<table>
		<tr>
			<td><?php echo Phalcon_Tag::image('img/book.png') ?></td>
			<td>
				<h2>Welcome</h2>
				Hi, welcome to Phalcon framework, a new approach on PHP frameworks. Our mission is
				to give you an advanced tool for developing web sites and applications without beign worried
				about losing performance.
			</td>
		</tr>
	</table>
</div>

<div class="doc-paragraph">
	<h3>What is Phalcon?</h3>
	Phalcon is an open source, full stack framework for PHP 5 written as a C-extension providing high performance.
	You don't have to learn or use C language, functionality is exposed as PHP classes you can use any time.
	Phalcon is also loose coupled thus you can select specific parts of the framework for your development.
</div>

<div class="doc-paragraph">
	Phalcon is not only about performance, our goal is to make it robust and easy to use!
</div>

<div class="nav-bar" align="right">
	<?php echo Phalcon_Tag::linkTo('documentation/toc', 'Table of Contents →') ?>
</div>
