<?php use Phalcon\Tag as Tag; ?>
<?php echo Tag::stylesheetLink("css/colors/zenburn.css") ?>

<div class="doc-box">
    <table width="60%" align="center">
        <tr>
            <td><?php echo Tag::image('img/book.png') ?></td>
            <td>
                <h2>Documentation</h2>
                Searching for the latest documentation for Phalcon? How does it
                work internally? Any examples available? This is the place for you!
            </td>
        </tr>
    </table>
</div>

<table align="center" class="tableFormat2" width="80%" cellspacing="15">
    <tr>
        <td valign="top">
            <h3>Documentation</h3>
            We are using <a href="http://readthedocs.org">Read The Docs</a> for our
            documentation. Each version has its own documentation, thus making it
            easier to find what you are looking for.
            <br />

            <h3>Resources</h3>
            Phalcon's documentation is maintained in Github repositories. You are
            more than welcome to send us pull requests if you found an error or
            if you want to add/modify an area that is not clear.
            <br />
            <br />
            Documentation regarding Phalcon and its usage can be found at:
            <br />
            <a href="http://docs.phalconphp.com/en/latest/index.html">Latest Phalcon Documentation</a>
            [<a href="https://github.com/phalcon/docs">Github Repo</a>]
            <ul>
                <li><a href="http://docs.phalconphp.com/en/0.6.0/index.html">0.6.0 (beta) Documentation (English)</a></li>
                <li><a href="http://docs.phalconphp.com/en/latest/index.html">0.5.0 (stable) Documentation (English)</a></li>
                <li><a href="http://docs.phalconphp.com/en/0.4.4/index.html">0.4.4 (old-stable) Documentation (English)</a></li>
            </ul>
            There is also documentation outlining the internal API of PhalconPHP.
            It can be found at:
            <br />
            <a href="http://internals.phalconphp.com/en/latest/index.html">Latest Internal API Documentation</a>
            [<a href="https://github.com/phalcon/docs-internals">Github Repo</a>]
            <br />

        </td>
    </tr>
</table>
