
<div class="nav-bar">
	<?php echo Phalcon_Tag::linkTo('index', 'Home') ?> » <?php echo Phalcon_Tag::linkTo('documentation/tools', 'Developer Tools') ?> » Linux
</div>

<div class="doc-paragraph">
	<h2>Phalcon Developer Tools on Linux</h2>
	These steps will guide you throught the process of install Phalcon Developer Tools on Linux platform.
</div>

<div class="doc-paragraph">
	<h3>Requisites</h3>
	PHP extension is required to execute Phalcon Tools. Be sure you have installed it previously.
</div>

<div class="doc-paragraph">
	<h3>Download</h3>
	You can download a cross platform package containing the developer tools from the
	<?php echo Phalcon_Tag::linkTo('download', 'download page') ?>. Also you can clone it
	from <a href="https://github.com/phalcon/phalcon-devtools">Github</a>.
</div>

<div class="doc-paragraph">
	Open your terminal and execute the commands as follows to get a rapid installation:
</div>

<div class="doc-paragraph image-center">
	<?php echo Phalcon_Tag::image(array('img/linux-1.png', 'width' => 550)) ?>
</div>

<div class="doc-paragraph">
	Then enter cloned directory and execute ". ./phalcon.sh", don't forget the dot at beginning of the command:
</div>

<div class="doc-paragraph image-center">
	<?php echo Phalcon_Tag::image(array('img/linux-2.png', 'width' => 550)) ?>
</div>

<div class="doc-paragraph">
	Congratulations you now have phalcon tools installed!
</div>

<div class="doc-paragraph">
	<h4>Related Guides</h4>
	<ul>
		<li><?php echo Phalcon_Tag::linkTo('documentation/tools', 'Using Developer Tools') ?></li>
		<li><?php echo Phalcon_Tag::linkTo('documentation/wintools', 'Installation on Windows') ?></li>
		<li><?php echo Phalcon_Tag::linkTo('documentation/mactools', 'Installation on Mac') ?></li>
	</ul>
</div>