
<div class="nav-bar">
	<?php echo Phalcon_Tag::linkTo('index', 'Home') ?> » Documentation
</div>

<div class="doc-paragraph">
	<h2>Table of Contents</h2>
</div>

<div class="doc-paragraph">
	<ul>
		<li><?php echo Phalcon_Tag::linkTo('documentation/index', 'Introduction') ?></li>
		<li>
			<?php echo Phalcon_Tag::linkTo('documentation/motivation', 'Our motivation') ?>
			<ul>
				<li><?php echo Phalcon_Tag::linkTo('documentation/motivation#why', 'Why?') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/motivation#how-php-works', 'How PHP works?') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/motivation#traditional-frameworks', 'How traditional PHP frameworks works?') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/motivation#extension-works', 'How a PHP C extension works?') ?></li>
			</ul>
		</li>
		<li>
			<?php echo Phalcon_Tag::linkTo('documentation/benchmark', 'Framework Benchmark') ?>
			<ul>
				<li><?php echo Phalcon_Tag::linkTo('documentation/benchmark#benchmark-made', 'How the bechmark was made?') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/benchmark#measures-taken', 'What measures does were taken?') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/benchmark#test-environment', 'What was the test environment?') ?></li>
			</ul>
		</li>
		<li>
			<?php echo Phalcon_Tag::linkTo('documentation/install', 'Installation') ?>
			<ul>
				<li>
					<?php echo Phalcon_Tag::linkTo('documentation/install#windows', 'Windows') ?>
					<ul>
						<li><?php echo Phalcon_Tag::linkTo('documentation/xampp', 'Detailed Installation on XAMPP for Windows') ?></li>
						<li><?php echo Phalcon_Tag::linkTo('documentation/wamp', 'Detailed Installation on WAMP for Windows') ?></li>
					</ul>
				</li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/install#unix', 'Unix/Linux') ?></li>
			</ul>
		</li>
		<li>
			<?php echo Phalcon_Tag::linkTo('documentation/tutorial', 'Tutorial') ?>
			<ul>
				<li><?php echo Phalcon_Tag::linkTo('documentation/tutorial#checking', 'Checking your installation') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/tutorial#creating-project', 'Creating a project') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/tutorial#pretty-urls', 'Pretty URLs') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/tutorial#bootstrap', 'Bootstrap') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/tutorial#creating-controller', 'Creating a Controller') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/tutorial#moving-view', 'Moving output to a view') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/tutorial#designing-form', 'Designing a sign up form') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/tutorial#model', 'Creating a Model') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/tutorial#database', 'Setting a Database Connection') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/tutorial#storing', 'Storing data using models') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/tutorial#conclusion', 'Conclusion') ?></li>
			</ul>
		</li>
		<li>
			<?php echo Phalcon_Tag::linkTo('documentation/mvc', 'The MVC Architecture') ?>
			<ul>
				<li><?php echo Phalcon_Tag::linkTo('documentation/mvc#models', 'Models') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/mvc#views', 'Views') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/mvc#controllers', 'Controllers') ?></li>
			</ul>
		</li>
		<li>
			<?php echo Phalcon_Tag::linkTo('documentation/controllers', 'Using Controllers') ?>
			<ul>
				<li><?php echo Phalcon_Tag::linkTo('documentation/controllers#dispatch-loop', 'Dispatch Loop') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/controllers#initializing', 'Initializing Controllers') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/controllers#dispatch-events', 'Dispatch Events') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/controllers#request-response', 'Request and Response') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/controllers#session-data', 'Session Data') ?></li>
			</ul>
		</li>
		<li>
			<?php echo Phalcon_Tag::linkTo('documentation/models', 'Working with Models') ?>
			<ul>
				<li><?php echo Phalcon_Tag::linkTo('documentation/models#creating', 'Creating Models') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/models#understanding', 'Understanding Record To Objects') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/models#finding', 'Finding Records') ?></li>
				<li>
					<?php echo Phalcon_Tag::linkTo('documentation/models#relationships', 'Relationships between Models') ?>
					<ul>
						<li><?php echo Phalcon_Tag::linkTo('documentation/models#unidirectional', 'Unidirectional relationships') ?></li>
						<li><?php echo Phalcon_Tag::linkTo('documentation/models#bidirectional', 'Bidirectional relations') ?></li>
						<li><?php echo Phalcon_Tag::linkTo('documentation/models#advantage-rels', 'Taking advantage of relationships') ?></li>
						<li><?php echo Phalcon_Tag::linkTo('documentation/models#virtual-fkeys', 'Virtual Foreign Keys') ?></li>
					</ul>
				</li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/models#creating-updating', 'Creating Updating/Records') ?>
					<ul>
						<li><?php echo Phalcon_Tag::linkTo('documentation/models#validation-messages', 'Validation Messages') ?></li>
						<li><?php echo Phalcon_Tag::linkTo('documentation/models#validation-events', 'Validation Events') ?></li>
						<li><?php echo Phalcon_Tag::linkTo('documentation/models#business-rule', 'Business Rule') ?></li>
						<li><?php echo Phalcon_Tag::linkTo('documentation/models#validating-data', 'Validating Data Integrity') ?></li>
					</ul>
				</li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/models#deleting', 'Deleting Records') ?>
				<li><?php echo Phalcon_Tag::linkTo('documentation/models#transactions', 'Transactions') ?>
				<li><?php echo Phalcon_Tag::linkTo('documentation/models#meta-data', 'Models Meta-Data') ?>
			</ul>
		</li>
		<li>
			<?php echo Phalcon_Tag::linkTo('documentation/views', 'Using Views') ?>
			<ul>
				<li><?php echo Phalcon_Tag::linkTo('documentation/views#controllers', 'Integrating Views with Controllers') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/views#partials', 'Using Partials') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/views#transfer', 'Transfer values from the controller to views') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/views#rendering', 'Control Rendering Levels') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/views#models', 'Using models at presentation') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/views#environment', 'View Environment') ?></li>
			</ul>
		</li>
		<li>
			<?php echo Phalcon_Tag::linkTo('documentation/tags', 'View Helpers') ?>
			<ul>
				<li><?php echo Phalcon_Tag::linkTo('documentation/tags#aliasing', 'Using Name Aliasing') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/tags#forms', 'Creating Forms') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/tags#form-elements', 'Helpers to Generate Form Elements') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/tags#select-boxes', 'Making Select Boxes') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/tags#assigning', 'Assigning HTML attributes') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/tags#setting', 'Setting Helper Values') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/tags#title', 'Changing dynamically the Document Title') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/tags#static', 'Static Content Helpers') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/tags#own', 'Creating your own helpers') ?></li>
			</ul>
		</li>
		<li>
			<?php echo Phalcon_Tag::linkTo('documentation/filter', 'Filtering and Sanitizing') ?>
			<ul>
				<li><?php echo Phalcon_Tag::linkTo('documentation/filter#sanitizing', 'Sanitizing data') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/filter#controllers', 'Sanitizing from Controllers') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/filter#filtering-parameters', 'Filtering Action Parameters') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/filter#filtering', 'Filtering data') ?></li>
			</ul>
		</li>
		<li>
			<?php echo Phalcon_Tag::linkTo('documentation/config', 'Reading Configurations') ?>
			<ul>
				<li><?php echo Phalcon_Tag::linkTo('documentation/config#adapters', 'File Adapters') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/config#arrays', 'Native Arrays') ?></li>
			</ul>
		</li>
		<li>
			<?php echo Phalcon_Tag::linkTo('documentation/pagination', 'Data Pagination') ?>
			<ul>
				<li><?php echo Phalcon_Tag::linkTo('documentation/pagination#adapters', 'Data Adapters') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/pagination#using', 'Using Paginators') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/pagination#page', 'Page Attributes') ?></li>
			</ul>
		</li>
		<li>
			<?php echo Phalcon_Tag::linkTo('documentation/cache', 'Improving Performance with Cache') ?>
			<ul>
				<li><?php echo Phalcon_Tag::linkTo('documentation/cache#when', 'When to implement cache?') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/cache#output', 'Caching Output Fragments') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/cache#data', 'Caching Arbitrary Data') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/cache#frontend', 'Frontend Adapters') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/cache#backend', 'Backend Adapters') ?></li>
			</ul>
		</li>
		<li>
			<?php echo Phalcon_Tag::linkTo('documentation/acl', 'Access Control Lists (ACL)') ?>
			<ul>
				<li><?php echo Phalcon_Tag::linkTo('documentation/acl#creating', 'Creating an ACL') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/acl#roles', 'Adding Roles to the ACL') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/acl#resources', 'Adding Resources') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/acl#access', 'Defining Access Controls') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/acl#querying', 'Querying an ACL') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/acl#inheritance', 'Roles Inheritance') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/acl#serializing', 'Serializing ACL lists') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/acl#controllers', 'Integrating ACL with Controllers') ?></li>
			</ul>
		</li>
		<li>
			<?php echo Phalcon_Tag::linkTo('documentation/intl', 'Internationalization') ?>
			<ul>
				<li><?php echo Phalcon_Tag::linkTo('documentation/intl#find', 'Find out best available Locale') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/intl#format', 'Formatting messages based on Locale') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/intl#collator', 'Locale-Sensitive comparision') ?></li>
			</ul>
		</li>
		<li>
			<?php echo Phalcon_Tag::linkTo('documentation/db', 'Database Abstraction Layer') ?>
			<ul>
				<li><?php echo Phalcon_Tag::linkTo('documentation/db#adapters', 'Database Adapters') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/db#dialects', 'Database Dialects') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/db#connecting', 'Connecting to Databases') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/db#pooling', 'Connection Pooling') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/db#finding', 'Finding Rows') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/db#ins-upd-del', 'Integrating ACL with Controllers') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/db#profiling', 'Profiling SQL Statements') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/db#logging', 'Logging SQL Statements') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/db#describing', 'Describing Tables and Databases') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/db#altering', 'Creating/Altering/Dropping Tables') ?></li>
			</ul>
		</li>
		<li>
			<?php echo Phalcon_Tag::linkTo('documentation/logging', 'Logging') ?>
			<ul>
				<li><?php echo Phalcon_Tag::linkTo('documentation/logging#adapters', 'Backend Adapters') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/logging#creating', 'Creating a Log') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/logging#transactions', 'Transactions') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/logging#format', 'Message Formatting') ?></li>
			</ul>
		</li>
		<li><?php echo Phalcon_Tag::linkTo('documentation/loader', 'Universal Class Loader') ?></li>
		<li>
			<?php echo Phalcon_Tag::linkTo('documentation/migrations', 'Database Migrations') ?>
			<ul>
				<li><?php echo Phalcon_Tag::linkTo('documentation/migrations#dumping', 'Schema Dumping') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/migrations#anatomy', 'Migration Class Anatomy') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/migrations#writing', 'Writing Migrations') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/migrations#running', 'Running Migrations') ?></li>
			</ul>
		</li>
		<li>
			<?php echo Phalcon_Tag::linkTo('documentation/tools', 'Using Developer Tools') ?>
			<ul>
				<li><?php echo Phalcon_Tag::linkTo('documentation/tools#installation', 'Installation') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/tools#getting', 'Getting Available Commands') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/tools#generating-project', 'Generating a Project Skeleton') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/tools#generating-controllers', 'Generating Controllers') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/tools#settings', 'Preparing Database Settings') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/tools#generating-models', 'Generating Models') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/tools#scaffold', 'Scaffold a CRUD') ?></li>
				<li><?php echo Phalcon_Tag::linkTo('documentation/tools#scaffold-bootstrap', 'Scaffold with Bootstrap') ?></li>
			</ul>
		</li>
		<li><?php echo Phalcon_Tag::linkTo('documentation/settings', 'Framework Settings') ?></li>
		<li><?php echo Phalcon_Tag::linkTo('api', 'Framework API') ?></li>
	</ul>
</div>

<div class="nav-bar">
	<table width="90%" align="center">
		<tr>
			<td align="left">
				<?php echo Phalcon_Tag::linkTo('documentation/index', '← Welcome') ?>
			</td>
			<td align="right">
				<?php echo Phalcon_Tag::linkTo('documentation/motivation', 'Our Motivation →') ?>
			</td>
		</tr>
	</table>
</div>