<div class="nav-bar">
	<?php echo Phalcon_Tag::linkTo('index', 'Home') ?> » Documentation
</div>

<div class="doc-paragraph">
	<h2>Multilingual Support</h2>
	The component Phalcon_Translate expects to help you creating multi-language applications.
	This type of applications require display content in multiple languages depending on the user's language.
</div>

<div class="doc-paragraph">
	<h3><a name="adapters">Adapters</a></h3>
	This component makes use of adapters to read translation messages from different sources in a unified way.
</div>

<div class="doc-paragraph">
	<table align="center" cellspacing="0">
		<tr>
			<th>Adapter</th>
			<th>Description</th>
		</tr>
		<tr>
			<td>Array</td>
			<td>Uses PHP arrays to store the messages. In terms of performance is the best.</td>
		</tr>
	</table>
</div>

<div class="nav-bar">
	<table width="90%" align="center">
		<tr>
			<td align="left">
				<?php echo Phalcon_Tag::linkTo('documentation/acl', '← Access Control Lists (ACL)') ?>
			</td>
			<td align="right">
				<?php echo Phalcon_Tag::linkTo('documentation/db', 'Database Abstraction Layer →') ?>
			</td>
		</tr>
	</table>
</div>
