
<div class="nav-bar">
	<?php echo Phalcon\Tag::linkTo('index', 'Home') ?> » <?php echo Phalcon\Tag::linkTo('documentation/install', 'Install') ?> » WAMP
</div>

<div class="doc-paragraph">
	<h2>Installation on WAMP</h2>
	<a href="http://www.wampserver.com/en/">WampServer</a> is a Windows web development environment.
	It allows you to create web applications with Apache2, PHP and a MySQL database.
	These are the detailed instructions to install Phalcon on WAMP for Windows. If possible, We recommend you
	to use the latest WAMP release.
</div>

<div class="doc-paragraph">
	<h3>Download the right Phalcon</h3>
	WAMP has both 32 and 64 bits versions. From the <?php echo Phalcon\Tag::linkTo('download', 'download section') ?>,
	you could choose the Phalcon for Windows accordingly to your desired architecture.
</div>

<div class="doc-paragraph">
	After download the Phalcon library you will have a zip file like this:
</div>

<div class="doc-paragraph image-center">
	<?php echo Phalcon\Tag::image('img/xampp-1.png') ?>
</div>

<div class="doc-paragraph">
	Extract the library from the archive to get the Phalcon DLL:
</div>

<div class="doc-paragraph image-center">
	<?php echo Phalcon\Tag::image('img/xampp-2.png') ?>
</div>

<div class="doc-paragraph">
	Copy the file php_phalcon.dll to the PHP extensions.
	We have installed WAMP at <i>c:\wamp</i> directory. In our case is located at <i>﻿C:\wamp\bin\php\php5.3.10\ext</i>
</div>

<div class="doc-paragraph image-center">
	<?php echo Phalcon\Tag::image('img/wamp-1.png') ?>
</div>

<div class="doc-paragraph">
	Edit the php.ini file, it is located at ﻿<i>﻿C:\wamp\bin\php\php5.3.10\php.ini</i>. It can be edited with Notepad or a similar program.
	Append at the end of the file: <i>extension=php_phalcon.dll</i> and save it.
</div>

<div class="doc-paragraph image-center">
	<?php echo Phalcon\Tag::image('img/wamp-2.png') ?>
</div>

<div class="doc-paragraph">
	Also edit another php.ini file, it is located at ﻿<i>﻿﻿C:\wamp\bin\apache\Apache2.2.21\bin\php.ini</i>.
	Append at the end of the file: <i>extension=php_phalcon.dll</i> and save it.
</div>

<div class="doc-paragraph">
	Now it's time to restart the Apache Web Server. Do a single click on the WampServer icon at system tray.
	Choose "Restart All Services" from the pop-up menu. Check out that tray icon will become green again.
</div>

<div class="doc-paragraph image-center">
	<?php echo Phalcon\Tag::image('img/wamp-3.png') ?>
</div>

<div class="doc-paragraph">
	Open your browser to navigate to http://localhost. The WAMP welcome page will appear. Look at the section "extensions loaded" to check if phalcon was loaded.
</div>

<div class="doc-paragraph image-center">
	<?php echo Phalcon\Tag::image('img/wamp-4.png') ?>
</div>

<div class="doc-paragraph">
	Congrats!, You are now flying with Phalcon.
</div>

<div class="doc-paragraph">
	<h4>Related Guides</h4>
	<ul>
		<li><?php echo Phalcon\Tag::linkTo('documentation/install', 'General Installation') ?></li>
		<li><?php echo Phalcon\Tag::linkTo('documentation/xampp', 'Detailed Installation on XAMP for Windows') ?></li>
	</ul>
</div>