
<div class="nav-bar">
	<?php echo Phalcon_Tag::linkTo('index', 'Home') ?> » <?php echo Phalcon_Tag::linkTo('documentation/tools', 'Developer Tools') ?> » Windows
</div>

<div class="doc-paragraph">
	<h2>Phalcon Developer Tools on Windows</h2>
	These steps will guide you throught the process of install Phalcon Developer Tools on Windows.
</div>

<div class="doc-paragraph">
	<h3>Requisites</h3>
	PHP extension is required to execute Phalcon Tools. Be sure you have installed it previously.
</div>

<div class="doc-paragraph">
	<h3>Download</h3>
	You can download a cross platform package containing the developer tools from the
	<?php echo Phalcon_Tag::linkTo('download', 'download page') ?>. Also you can clone it
	from <a href="https://github.com/phalcon/phalcon-devtools">Github</a>.
</div>

<div class="doc-paragraph">
	On the Windows platform, you need to configure the system PATH to include phalcon tools and the PHP
	executable as well.
</div>

<div class="doc-paragraph">
	If you download the phalcon tools as a zip archive, extract it on any path of your local drive.
	By example <i>c:\phalcon-tools</i> or something like that. You will need this path in the steps below.
</div>

<div class="doc-paragraph">
	Edit the file "phalcon.bat" by doing right click and choosing option "Edit":
</div>

<div class="doc-paragraph image-center">
	<?php echo Phalcon_Tag::image('img/path-0.png') ?>
</div>

<div class="doc-paragraph">
	Change the path you did installed the phalcon tools:
</div>

<div class="doc-paragraph image-center">
	<?php echo Phalcon_Tag::image('img/path-01.png') ?>
</div>

<div class="doc-paragraph">
	Save the changes on the edited file.
</div>

<div class="doc-paragraph">
	<h4>Adding PHP and Tools to your system PATH</h4>
	Because the scripts are written in PHP, you need to install it in your machine.
	Depending of your kind of PHP installation, it can be located at different places. Search the file
	php.exe and copy the path it was found. For example, when using the last WAMP stack, PHP is located at:
	<i>﻿C:\wamp\bin\php\php5.3.10\php.exe</i>
</div>

<div class="doc-paragraph">
	From the Windows start menu, do right click on icon "My Computer", a context menu will appear, then choose the option "Properties":
</div>

<div class="doc-paragraph image-center">
	<?php echo Phalcon_Tag::image('img/path-1.png') ?>
</div>

<div class="doc-paragraph">
	Now, select the tab "Advanced" and then click on the button "Environment Variables":
</div>

<div class="doc-paragraph image-center">
	<?php echo Phalcon_Tag::image('img/path-2.png') ?>
</div>

<div class="doc-paragraph">
	At the bottom, look for the section "System variables" and edit the variable "Path":
</div>

<div class="doc-paragraph image-center">
	<?php echo Phalcon_Tag::image('img/path-3.png') ?>
</div>

<div class="doc-paragraph">
	Be careful at this part, append at the end of variable value the path you found the
	PHP executable and the Path where phalcon tools was installed. Use the ";" character to separate
	the differents paths in the variable:
</div>

<div class="doc-paragraph image-center">
	<?php echo Phalcon_Tag::image('img/path-4.png') ?>
</div>

<div class="doc-paragraph">
	Accept the changes made by clicking on the button "OK" and close the dialogs opened. From the start menu click
	on the option "Run". If you can't find this option, press "Windows Key" + "R".
</div>

<div class="doc-paragraph image-center">
	<?php echo Phalcon_Tag::image('img/path-5.png') ?>
</div>

<div class="doc-paragraph">
	Type "cmd" and press enter to open the windows command line utility:
</div>

<div class="doc-paragraph image-center">
	<?php echo Phalcon_Tag::image('img/path-6.png') ?>
</div>

<div class="doc-paragraph">
	Type the commands "php -v" and "phalcon" you will look something like this:
</div>

<div class="doc-paragraph image-center">
	<?php echo Phalcon_Tag::image('img/path-7.png') ?>
</div>

<div class="doc-paragraph">
	Congratulations you now have phalcon tools installed!
</div>

<div class="doc-paragraph">
	<h4>Related Guides</h4>
	<ul>
		<li><?php echo Phalcon_Tag::linkTo('documentation/tools', 'Using Developer Tools') ?></li>
		<li><?php echo Phalcon_Tag::linkTo('documentation/mactools', 'Installation on OS X') ?></li>
	</ul>
</div>