    <meta name="msapplication-TileColor" content="#FFFFFF">
    <meta name="msapplication-square70x70logo"
              content="https://assets.phalcon.io/phalcon/favicons/mstile-70x70.png">
    <meta name="msapplication-TileImage"
          content="https://assets.phalcon.io/phalcon/favicons/mstile-144x144.png">
    <meta name="msapplication-square150x150logo"
          content="https://assets.phalcon.io/phalcon/favicons/mstile-150x150.png">
    <meta name="msapplication-wide310x150logo"
          content="https://assets.phalcon.io/phalcon/favicons/mstile-310x150.png">
    <meta name="msapplication-square310x310logo"
          content="https://assets.phalcon.io/phalcon/favicons/mstile-310x310.png">

    <link rel="apple-touch-icon"
          href="https://assets.phalcon.io/phalcon/favicons/apple-touch-icon.png">

    <link rel="apple-touch-icon-precomposed"
          sizes="57x57"
          href="https://assets.phalcon.io/phalcon/favicons/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon-precomposed"
          sizes="60x60"
          href="https://assets.phalcon.io/phalcon/favicons/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon-precomposed"
          sizes="72x72"
          href="https://assets.phalcon.io/phalcon/favicons/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon-precomposed"
          sizes="76x76"
          href="https://assets.phalcon.io/phalcon/favicons/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon-precomposed"
          sizes="114x114"
          href="https://assets.phalcon.io/phalcon/favicons/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon-precomposed"
          sizes="120x120"
          href="https://assets.phalcon.io/phalcon/favicons/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon-precomposed"
          sizes="144x144"
          href="https://assets.phalcon.io/phalcon/favicons/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon-precomposed"
          sizes="152x152"
          href="https://assets.phalcon.io/phalcon/favicons/apple-touch-icon-152x152.png">

    <link rel="icon"
          type="image/png"
          sizes="16x16"
          href="https://assets.phalcon.io/phalcon/favicons/favicon-16x16.png">
    <link rel="icon"
          type="image/png"
          sizes="32x32"
          href="https://assets.phalcon.io/phalcon/favicons/favicon-32x32.png">
    <link rel="icon"
          type="image/png"
          sizes="96x96"
          href="https://assets.phalcon.io/phalcon/favicons/favicon-96x96.png">
    <link rel="icon"
          type="image/png"
          sizes="128x128"
          href="https://assets.phalcon.io/phalcon/favicons/favicon-128x128.png">
    <link rel="icon"
          type="image/png"
          sizes="196x196"
          href="https://assets.phalcon.io/phalcon/favicons/favicon-196x196.png">
    <link rel="shortcut icon"
          type="image/png"
          href="https://assets.phalcon.io/phalcon/favicons/favicon.ico"/>
