
<div class="about">

<h2>Get Involved</h2>

<p>
Hey, thanks for reading this page!
</p>

<p>
We all make Phalcon. We might not know you just yet, but we think you'd be a great fit for building a better web.
Together, we're ready to change the world.
</p>

<p>
Here at Phalcon, we’re building a new generation of frameworks for PHP, we want to give you an amazing performance while helping you develop easy and fun.
</p>

<p>
We hope that you enjoy Phalcon as much as we do. Our doors are always open to receive your collaboration with the many things a project like this require.
</p>

<p>
Contributing to Phalcon comes in all different shapes and sizes. Whether you're a user helping us find bugs, providing feedback on our mailing lists, or contributing code or design, we need you.
</p>

<p>
Also, we’re a tiny core team of developers working our tails off, all the support you can provide to the project is really appreciate.
</p>

<p>
PS: We love travel, know other cultures and work in interesting projects across the world. If you have something interesting for us,
please write us to <a href="mailto:team@phalconphp.com">team@phalconphp.com</a> or mention us on twitter <a href="http://twitter.com/phalconphp">@phalconphp</a>.
</p>

<p>
With Love, Phalcon Team <3
</p>

</div>