<?php use Phalcon\Tag as Tag; ?>
<?php echo Tag::stylesheetLink("css/colors/zenburn.css") ?>

<div class="doc-box">
    <table width="60%" align="center">
        <tr>
            <td><?php echo Tag::image('img/download.png') ?></td>
            <td>
                <h2>Support</h2>
                Got stuck somewhere? Usage questions? Curious about the project or a feature? You are in the right place!
            </td>
        </tr>
    </table>
</div>

<table align="center" class="tableFormat2" width="80%" cellspacing="15">
    <tr>
        <td valign="top">
            <h3>Support</h3>
            Having problems using PhalconPHP? You're in the right place!
            <br />

            <h3>Latest version</h3>
            Many bugs raised because users are not running the latest version.
            Please visit the <?php echo Tag::linkTo('download', 'download'); ?> page
            and confirm if the issue you are experiencing is indeed a bug.
            <br />

            <h3>Documentation</h3>
            Please use the <?php echo Tag::linkTo('documentation', 'documentation'); ?>
            before anything else. You can also use the search feature in our documents
            to find what you are looking for. If your question is still not answered,
            there are more options below.

            <h3>Google Groups</h3>
            You can also ask a question in our
            <a href="https://groups.google.com/forum/#!forum/phalcon">Google Group</a>.

            <h3>Stack Overflow</h3>
            If you are familiar or prefer Stack Overflow, there is a
            <a href="http://stackoverflow.com/questions/tagged/phalcon">phalcon</a>
            tag that you can use to search or to tag your query.

            Please note:
            <ul>
                <li>Stack Overflow is not dedicated to support Phalcon</li>
                <li>Please do not raise new bugs there. Please use the
                    <a href="https://github.com/phalcon/cphalcon/issues">issue tracker</a> in Github for that</li>
                <li>Please do not ask for feature requests there. Please use the
                    <a href="https://github.com/phalcon/cphalcon/issues">issue tracker</a> in Github for that</li>
                <li>Make sure you include the "phalcon" tag with your question</li>
                <li>Make sure you mention "Phalcon" in the question</li>
            </ul>

            <h3>Reporting a bug</h3>
            Please report bugs when you've exhausted all of the above options, using
            the <a href="https://github.com/phalcon/cphalcon/issues">issue tracker</a>
            in Github.

        </td>
    </tr>
</table>
