<div id="header">
	<h1>
		<?php echo Phalcon\Tag::linkTo('index', Phalcon\Tag::image(array('img/logo-small.png', 'border' => 0))) ?>
	</h1>
	<div align="center">
		<div id="nav-main" role="navigation">
			<div class="menubar">
				<div class="nav-main-features nav-first">
					<?php echo Phalcon\Tag::linkTo('index', 'HOME'); ?>
				</div>
				<div class="nav-main-features nav-first">
					<?php echo Phalcon\Tag::linkTo('download', 'DOWNLOAD'); ?>
				</div>
				<div class="nav-main-features">
					<?php echo Phalcon\Tag::linkTo('documentation', 'DOCUMENTATION'); ?>
				</div>
				<div class="nav-main-features">
					<a href="https://groups.google.com/forum/#!forum/phalcon">SUPPORT</a>
				</div>
				<div class="nav-main-features nav-first">
					<a href="https://github.com/phalcon/cphalcon">GITHUB</a>
				</div>
				<div class="nav-main-features">
					<a target="blog" href="http://blog.phalconphp.com/">BLOG</a>
				</div>
			</div>
		</div>
	</div>
</div>

<?php echo $this->getContent(); ?>

<div id="footer" align="center">
	<table class="footer-table">
		<tr>
			<td class="social tweets" align="left" valign="top">
				<p>
	                <label>Follow and Tweet</label>
					<div id="tweet">
						<p>Please wait while our updates load</p>
					</div>
					<a href="https://twitter.com/phalconphp" class="twitter-follow-button" data-show-count="false">Follow @phalconphp</a>
				</p>
			</td>
			<td class="social" align="left" valign="top">
				<p>
					<label>Social</label><br/>
					<a href="http://twitter.com/phalconphp">Follow us on Twitter</a><br/>
					<a href="http://www.facebook.com/pages/Phalcon/134230726685897">Facebook Page</a><br/>
					<a href="https://plus.google.com/102376109340560896457">Google+ Page</a><br/>
					<a href="http://blog.phalconphp.com">Official Blog</a><br/>
				</p>
				<p>
					<label>Support</label><br/>
					<a href="https://github.com/phalcon/cphalcon/issues">Issues at Github</a><br/>
					<a href="http://phalcon.uservoice.com/">Feedback & Support</a><br/>
					<a href="http://webchat.freenode.net/?channels=phalconphp">IRC Channel</a><br/>
					<a href="https://groups.google.com/forum/#!forum/phalcon">Mailing List</a>
				</p>
				<p>
					<label>Get Involved</label><br/>
					<?php echo Phalcon\Tag::linkTo('about', 'About') ?><br/>
					<a href="https://github.com/phalcon/cphalcon/wiki/Roadmap">Roadmap</a>
				</p>
			</td>
			<td class="subscribe" align="left" valign="top">
				<p>
					<label>Get Monthly News</label><br/>
					<?php echo Phalcon\Tag::form('index/subscribe') ?>
						<table>
							<tr>
								<td><?php echo Phalcon\Tag::textField(array('email', 'placeholder' => 'Your email address', 'size' => 25)) ?></td>
								<td><?php echo Phalcon\Tag::submitButton('Subscribe') ?></td>
							</tr>
						</table>
					</form>
				</p>
			</td>
		</tr>
	</table>
</div>

